name: Playwright Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: UI Tests

    steps:
      - name: Checkout 🚀🚀
        uses: actions/checkout@v4

      - name: Setup Python 🔧🔧
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies ➕➕
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright ➕➕
        run: python -m playwright install --with-deps

      - name: Run tests 🧪🧪
        run: pytest --html=reports/report.html tests/submitForm.py

      - name: Publish Reports 📄📄
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Playwright-Reports
          path: reports
          retention-days: 90
          if-no-files-found: warn

